site:
  title: My Custa Site
  theme: dark
  language: ru

layout:
  template_dir: themes/{theme}/templates
  stylesheet_dir: themes/{theme}/css

pages:
  "/":
    file: index.kms
    title: Главная

  "/table":
    file: table.kms
    title: Таблицы

  "/author":
    file: author.kms
    title: Автор
  
  "/test":
    file: test.kms
    title: test
